### PR TITLE
initial required updates

### PR DESCRIPTION
**Pull request by katietz**

### CODE REVIEW

**Review by varlackc — COMMENTED** [review]
This seems to be a new build, not sure why we are using such a large `build number` in this particular case. 

https://github.com/AnacondaRecipes/perl-xml-parser-feedstock/blob/a8aa4a738b5cebbe1ea07a41e5f19f105cfe131e/recipe/meta.yaml#L15

In addition we mighe benefit from adding a description to the recipe. The following `description` could be useful:

description: This module provides ways to parse XML documents. It is built on top of XML::Parser::Expat, which is a lower level interface to James Clark's expat library.

**Review by ELundby45 — APPROVED** [review]
Agreed with resetting the build number and adding a description. Beyond that, LGTM

**Comment by katietz** [comment]
well, I took the build-number from CF's recipe.  Sometimes this number has a meaning in dependencies, which can be problematic to reset.  Anyway, I reset it to 0 and added the description.  thanks

**Comment by katietz** [comment]
I see it as reviewed 2 times, and will merged. thank you!

**Pull request merged**
